version: "3.9"
services:
  native-mcp-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://149.165.175.102:8050/sse
      - BENCHMARK_RUNS=100
      - MODELCARD_ID=megadetector-mc
      - SEARCH_QUERY=megadetector
      - CLIENT_TYPE=native
      - BENCHMARK_RESULTS_DIR=/app/benchmark_results
      - SEARCH_MODELCARDS_PATH=/modelcards/search

    network_mode: "host"
    volumes:
      - ./benchmark_results:/app/benchmark_results:rw
      
  layered-mcp-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://149.165.175.102:8051/sse
      - BENCHMARK_RUNS=100
      - MODELCARD_ID=megadetector-mc
      - SEARCH_QUERY=megadetector
      - CLIENT_TYPE=layered
      - BENCHMARK_RESULTS_DIR=/app/benchmark_results
    network_mode: "host"
    volumes:
      - ./benchmark_results:/app/benchmark_results:rw