version: "3.9"
services:
  mcp-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://149.165.175.102:8050/sse
      - BENCHMARK_RUNS=10
      - MODELCARD_ID=megadetector-mc
      - SEARCH_QUERY=megadetector
      - GET_MODELCARD_PATH=/modelcard/{mc_id}
      - SEARCH_MODELCARDS_PATH=/modelcards/search

    network_mode: "host"
    volumes:
      - ./benchmark_results:/app/benchmark_results:rw
