version: "3.9"
services:
  mcp-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BENCHMARK_RUNS=100
      - MODELCARD_ID=megadetector-mc
      - SEARCH_QUERY=megadetector
      - BENCHMARK_RESULTS_DIR=/app/benchmark_results
    network_mode: "host"
    volumes:
      - ./benchmark_results:/app/benchmark_results:rw