version: "3.9"
services:
  analysis:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_DIR=/inputs/db
      - MCP_RESULTS_DIR=/inputs/mcp
      - REST_RESULTS_DIR=/inputs/rest
      - ANALYSIS_OUTPUT_DIR=/outputs

    volumes:
      - ../mcp/benchmark_results:/inputs/mcp:ro
      - ../rest/benchmark_results:/inputs/rest:ro
      - ../db/benchmark_results:/inputs/db:ro
      - ./outputs:/outputs:rw

