version: "3.9"
services:
  rest-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://149.165.175.102:5002
      - BENCHMARK_RUNS=1000
      - MODELCARD_ID=3f7b2c82-75fa-4335-a3b8-e1930893a974
      - SEARCH_QUERY=AlexNet
      - GET_MODELCARD_PATH=/modelcard/{mc_id}
      - SEARCH_MODELCARDS_PATH=/modelcards/search
      - THROUGHPUT_DURATION=10
      - MAX_CONCURRENT=50
      - MEASURE_THROUGHPUT=true
      
    network_mode: "host"
    volumes:
      - ./benchmark_results:/app/benchmark_results:rw


